@extends('sections.layout')
@section('content')
  <game-menu></game-menu>
  <deck-builder></deck-builder>
  <create-profile></create-profile>
  <versus-menu></versus-menu>
  <game-list></game-list>
  <leaderboard></leaderboard>
@endsection('content')
